---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-scripts
  namespace: {{ .Values.namespace }}
data:
  90-create-application.sql: |-
{{ include ( print $.Template.BasePath "/_90-create-application.sql") . | indent 4 }}
  91-insert-admin.sql: |-
{{ include ( print $.Template.BasePath "/_91-insert-admin.sql") . | indent 4 }}
