---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: node
        image: "opla/backend:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8081
        - containerPort: 9229
        readinessProbe:
          httpGet:
            path: /api/v1/
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: OPLA_BACKEND_DATABASE_HOST
          value: {{ .Values.db.host }}
        - name: OPLA_BACKEND_DATABASE_PORT
          value: "3306"
        - name: OPLA_BACKEND_DATABASE_NAME
          value: {{ .Values.db.name }}
        - name: OPLA_BACKEND_DATABASE_USER
          value: {{ .Values.db.user }}
        - name: OPLA_BACKEND_DATABASE_PASS
          value: {{ .Values.db.password }}
        - name: PORT
          value: "8081"
        - name: SKIP_MIGRATION
          value: "false"

--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 80
      - path: /auth
        backend:
          serviceName: backend
          servicePort: 80
  {{- if eq .Values.tls true }}
  tls:
    - secretName: {{ .Values.api.domain | replace "." "-" }}-tls
      hosts:
        - {{ .Values.api.domain }}
  {{- end }}
